version: '3'

services:
  frontend:
    container_name: service_front_end
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  backend:
    container_name: service_back_end
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl
      - ./logs:/var/log/nginx
      - ./certs_webroot:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs_webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



networks:
  app-network:
    driver: bridge
