version: '3'

services:
  frontend:
    container_name: service_front_end
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  backend:
    container_name: service_back_end
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
